#!/bin/bash
# 此脚本在Imagebuilder 根目录运行
source custom-packages.sh
echo "第三方软件包: $CUSTOM_PACKAGES"
LOGFILE="/tmp/uci-defaults-log.txt"
echo "Starting 99-custom.sh at $(date)" >> $LOGFILE

if [ -z "$CUSTOM_PACKAGES" ]; then
  echo "⚪️ 未选择 任何第三方软件包"
else
  # ============= 同步第三方插件库==============
  # 同步第三方软件仓库run/ipk
  echo "🔄 正在同步第三方软件仓库 Cloning run file repo..."
  git clone --depth=1 https://github.com/wukongdaily/store.git /tmp/store-run-repo

  # 拷贝 run/arm64 下所有 run 文件和ipk文件 到 extra-packages 目录
  mkdir -p extra-packages
  cp -r /tmp/store-run-repo/run/arm64/* extra-packages/

  echo "✅ Run files copied to extra-packages:"
  ls -lh extra-packages/*.run
  # 解压并拷贝ipk到packages目录
  sh prepare-packages.sh
  echo "打印imagebuilder/packages目录结构"
  ls -lah packages/ |grep partexp
fi

# 输出调试信息
echo "$(date '+%Y-%m-%d %H:%M:%S') - 开始构建固件..."

# ============= iStoreOS 24.10 官方集成插件===================
# ============= 若启用 则打开注释 ============================

# 定义初始化变量
PACKAGES=""

# iStoreOS官方集成列表，若启用则打开注释
#PACKAGES="$PACKAGES adb"
#PACKAGES="$PACKAGES adb-enablemodem"
# --------------------------------------------------------
# 核心基础 (必须保留)
# --------------------------------------------------------
PACKAGES="$PACKAGES attr"
PACKAGES="$PACKAGES base-files"
PACKAGES="$PACKAGES bash"
PACKAGES="$PACKAGES busybox"
PACKAGES="$PACKAGES bzip2"
PACKAGES="$PACKAGES ca-bundle"
PACKAGES="$PACKAGES ca-certificates"
PACKAGES="$PACKAGES cgi-io"
PACKAGES="$PACKAGES coreutils"
PACKAGES="$PACKAGES coreutils-stat"
PACKAGES="$PACKAGES coreutils-stty"
PACKAGES="$PACKAGES curl"
PACKAGES="$PACKAGES dropbear"
PACKAGES="$PACKAGES e2fsprogs"
PACKAGES="$PACKAGES ethtool"
PACKAGES="$PACKAGES fstools"
PACKAGES="$PACKAGES fwtool"
PACKAGES="$PACKAGES getrandom"
PACKAGES="$PACKAGES htop"
PACKAGES="$PACKAGES ip-full"
PACKAGES="$PACKAGES iptables-mod-conntrack-extra"
PACKAGES="$PACKAGES iptables-mod-extra"
PACKAGES="$PACKAGES iptables-nft"
PACKAGES="$PACKAGES istoreos-files"
PACKAGES="$PACKAGES jshn"
PACKAGES="$PACKAGES jsonfilter"
PACKAGES="$PACKAGES kernel"
PACKAGES="$PACKAGES logd"
PACKAGES="$PACKAGES lsblk"
PACKAGES="$PACKAGES lscpu"
PACKAGES="$PACKAGES lua"
PACKAGES="$PACKAGES map"
PACKAGES="$PACKAGES mount-utils"
PACKAGES="$PACKAGES mtd"
PACKAGES="$PACKAGES netifd"
PACKAGES="$PACKAGES nftables-json"
PACKAGES="$PACKAGES openssl-util"
PACKAGES="$PACKAGES openwrt-keyring"
PACKAGES="$PACKAGES opkg"
PACKAGES="$PACKAGES procd"
PACKAGES="$PACKAGES procd-seccomp"
PACKAGES="$PACKAGES procd-ujail"
PACKAGES="$PACKAGES procps-ng"
PACKAGES="$PACKAGES procps-ng-vmstat"
PACKAGES="$PACKAGES resolveip"
PACKAGES="$PACKAGES rpcd"
PACKAGES="$PACKAGES rpcd-mod-file"
PACKAGES="$PACKAGES rpcd-mod-luci"
PACKAGES="$PACKAGES rpcd-mod-rrdns"
PACKAGES="$PACKAGES rpcd-mod-ucode"
PACKAGES="$PACKAGES script-utils"
PACKAGES="$PACKAGES shadow"
PACKAGES="$PACKAGES shadow-chage"
PACKAGES="$PACKAGES shadow-chfn"
PACKAGES="$PACKAGES shadow-chgpasswd"
PACKAGES="$PACKAGES shadow-chpasswd"
PACKAGES="$PACKAGES shadow-chsh"
PACKAGES="$PACKAGES shadow-common"
PACKAGES="$PACKAGES shadow-expiry"
PACKAGES="$PACKAGES shadow-faillog"
PACKAGES="$PACKAGES shadow-gpasswd"
PACKAGES="$PACKAGES shadow-groupadd"
PACKAGES="$PACKAGES shadow-groupdel"
PACKAGES="$PACKAGES shadow-groupmems"
PACKAGES="$PACKAGES shadow-groupmod"
PACKAGES="$PACKAGES shadow-groups"
PACKAGES="$PACKAGES shadow-grpck"
PACKAGES="$PACKAGES shadow-grpconv"
PACKAGES="$PACKAGES shadow-grpunconv"
PACKAGES="$PACKAGES shadow-lastlog"
PACKAGES="$PACKAGES shadow-login"
PACKAGES="$PACKAGES shadow-logoutd"
PACKAGES="$PACKAGES shadow-newgidmap"
PACKAGES="$PACKAGES shadow-newgrp"
PACKAGES="$PACKAGES shadow-newuidmap"
PACKAGES="$PACKAGES shadow-newusers"
PACKAGES="$PACKAGES shadow-nologin"
PACKAGES="$PACKAGES shadow-passwd"
PACKAGES="$PACKAGES shadow-pwck"
PACKAGES="$PACKAGES shadow-pwconv"
PACKAGES="$PACKAGES shadow-pwunconv"
PACKAGES="$PACKAGES shadow-su"
PACKAGES="$PACKAGES shadow-useradd"
PACKAGES="$PACKAGES shadow-userdel"
PACKAGES="$PACKAGES shadow-usermod"
PACKAGES="$PACKAGES shadow-utils"
PACKAGES="$PACKAGES shadow-vipw"
PACKAGES="$PACKAGES swap-utils"
PACKAGES="$PACKAGES sysfsutils"
PACKAGES="$PACKAGES sysstat"
PACKAGES="$PACKAGES tar"
PACKAGES="$PACKAGES terminfo"
PACKAGES="$PACKAGES ubox"
PACKAGES="$PACKAGES ubus"
PACKAGES="$PACKAGES ubusd"
PACKAGES="$PACKAGES uci"
PACKAGES="$PACKAGES uclient-fetch"
PACKAGES="$PACKAGES ucode"
PACKAGES="$PACKAGES ucode-mod-fs"
PACKAGES="$PACKAGES ucode-mod-html"
PACKAGES="$PACKAGES ucode-mod-lua"
PACKAGES="$PACKAGES ucode-mod-math"
PACKAGES="$PACKAGES ucode-mod-ubus"
PACKAGES="$PACKAGES ucode-mod-uci"
PACKAGES="$PACKAGES ucode-mod-uloop"
PACKAGES="$PACKAGES uhttpd"
PACKAGES="$PACKAGES uhttpd-mod-ubus"
PACKAGES="$PACKAGES unzip"
PACKAGES="$PACKAGES urandom-seed"
PACKAGES="$PACKAGES urngd"
PACKAGES="$PACKAGES usign"
PACKAGES="$PACKAGES wget-ssl"
PACKAGES="$PACKAGES xtables-nft"
PACKAGES="$PACKAGES xz"
PACKAGES="$PACKAGES xz-utils"
PACKAGES="$PACKAGES zlib"
PACKAGES="$PACKAGES zram-swap"
PACKAGES="$PACKAGES -libustream-mbedtls"

# --------------------------------------------------------
# 核心依赖修复包 (解决Error )
# --------------------------------------------------------
PACKAGES="$PACKAGES -dnsmasq"         # 确保移除冲突的 dnsmasq 基础版 (如果存在)
PACKAGES="$PACKAGES libiptext6-0"     # IPv6 核心库（即使不用，编译时也可能被依赖）
PACKAGES="$PACKAGES libiptext-nft0"   # Netfilter/NFTables 核心 IP 文本库
PACKAGES="$PACKAGES libiptext0"       # Netfilter/NFTables 核心 IP 文本库
PACKAGES="$PACKAGES liblua5.1.5"      # 核心 Lua 运行时库
PACKAGES="$PACKAGES libubus-lua"      # UBUS (OpenWrt 进程通信) 的 Lua 绑定
PACKAGES="$PACKAGES libuci-lua"       # UCI (OpenWrt 配置系统) 的 Lua 绑定
PACKAGES="$PACKAGES ubus"             # UBUS 守护程序 (核心进程通信)
PACKAGES="$PACKAGES libiwinfo-lua"    # LuCI 界面查询信息所需的 Lua 绑定
PACKAGES="$PACKAGES luci-proto-ipv6"  # 修复 LuCI 网络配置页面的依赖链（即使不用，LuCI 也依赖）
PACKAGES="$PACKAGES coreutils-nohup"  # 修复 netspeedtest 依赖
PACKAGES="$PACKAGES kmod-crypto-core" # 核心加密模块 (修复 kmod-crypto-core 缺失)
PACKAGES="$PACKAGES kmod-nf-core"     # 核心防火墙模块 (修复 kmod-nf-core 缺失)

# --------------------------------------------------------
# 核心驱动模块 (RK3566 和 RTL8211F 必须保留)
# --------------------------------------------------------
PACKAGES="$PACKAGES kmod-block2mtd"
PACKAGES="$PACKAGES kmod-crypto-aead"
PACKAGES="$PACKAGES kmod-crypto-authenc"
PACKAGES="$PACKAGES kmod-crypto-cbc"
PACKAGES="$PACKAGES kmod-crypto-cmac"
PACKAGES="$PACKAGES kmod-crypto-core"
PACKAGES="$PACKAGES kmod-crypto-crc32c"
PACKAGES="$PACKAGES kmod-crypto-ctr"
PACKAGES="$PACKAGES kmod-crypto-deflate"
PACKAGES="$PACKAGES kmod-crypto-des"
PACKAGES="$PACKAGES kmod-crypto-ecb"
PACKAGES="$PACKAGES kmod-crypto-echainiv"
PACKAGES="$PACKAGES kmod-crypto-geniv"
PACKAGES="$PACKAGES kmod-crypto-hash"
PACKAGES="$PACKAGES kmod-crypto-hmac"
PACKAGES="$PACKAGES kmod-crypto-manager"
PACKAGES="$PACKAGES kmod-crypto-md5"
PACKAGES="$PACKAGES kmod-crypto-null"
PACKAGES="$PACKAGES kmod-crypto-rng"
PACKAGES="$PACKAGES kmod-crypto-sha1"
PACKAGES="$PACKAGES kmod-crypto-sha256"
PACKAGES="$PACKAGES kmod-dm"
PACKAGES="$PACKAGES kmod-dnsresolver"
PACKAGES="$PACKAGES kmod-dma-buf"
PACKAGES="$PACKAGES kmod-dwmac-rockchip"  # RK3566 以太网 MAC 驱动
PACKAGES="$PACKAGES kmod-fs-ext4"        # 核心文件系统
PACKAGES="$PACKAGES kmod-fs-vfat"        # 基础文件系统
PACKAGES="$PACKAGES kmod-fuse"
PACKAGES="$PACKAGES kmod-lib-crc-ccitt"
PACKAGES="$PACKAGES kmod-lib-crc-itu-t"
PACKAGES="$PACKAGES kmod-lib-crc16"
PACKAGES="$PACKAGES kmod-lib-crc32c"
PACKAGES="$PACKAGES kmod-lib-crc7"
PACKAGES="$PACKAGES kmod-lib-crc8"
PACKAGES="$PACKAGES kmod-lib-lzo"
PACKAGES="$PACKAGES kmod-lib-textsearch"
PACKAGES="$PACKAGES kmod-lib-xor"
PACKAGES="$PACKAGES kmod-lib-xxhash"
PACKAGES="$PACKAGES kmod-lib-zlib-deflate"
PACKAGES="$PACKAGES kmod-lib-zlib-inflate"
PACKAGES="$PACKAGES kmod-libphy"
PACKAGES="$PACKAGES kmod-loop"
PACKAGES="$PACKAGES kmod-mdio"
PACKAGES="$PACKAGES kmod-mii"
PACKAGES="$PACKAGES kmod-mmc"
PACKAGES="$PACKAGES kmod-nf-conntrack"
PACKAGES="$PACKAGES kmod-nf-core"
PACKAGES="$PACKAGES kmod-nf-flow"
PACKAGES="$PACKAGES kmod-nf-ipt"
PACKAGES="$PACKAGES kmod-nf-log"
PACKAGES="$PACKAGES kmod-nf-nat"
PACKAGES="$PACKAGES kmod-nf-nathelper"
PACKAGES="$PACKAGES kmod-nf-nathelper-extra"
PACKAGES="$PACKAGES kmod-nf-reject"
PACKAGES="$PACKAGES kmod-nfnetlink"
PACKAGES="$PACKAGES kmod-nft-compat"
PACKAGES="$PACKAGES kmod-nft-core"
PACKAGES="$PACKAGES kmod-nls-base"
PACKAGES="$PACKAGES kmod-nls-cp437"
PACKAGES="$PACKAGES kmod-nls-iso8859-1"
PACKAGES="$PACKAGES kmod-nls-utf8"
PACKAGES="$PACKAGES kmod-of-mdio"
PACKAGES="$PACKAGES kmod-phy-realtek"    # RTL8211F PHY 驱动 (重要)
PACKAGES="$PACKAGES kmod-phylink"
PACKAGES="$PACKAGES kmod-pps"
PACKAGES="$PACKAGES kmod-ptp"
PACKAGES="$PACKAGES kmod-random-core"
PACKAGES="$PACKAGES kmod-regmap-core"
PACKAGES="$PACKAGES kmod-regmap-i2c"
PACKAGES="$PACKAGES kmod-sched-core"
PACKAGES="$PACKAGES kmod-scsi-core"
PACKAGES="$PACKAGES kmod-slhc"
PACKAGES="$PACKAGES kmod-stmmac-core"
PACKAGES="$PACKAGES kmod-thermal"
PACKAGES="$PACKAGES kmod-tun"
PACKAGES="$PACKAGES kmod-usb-core"
PACKAGES="$PACKAGES kmod-usb-dwc2"
PACKAGES="$PACKAGES kmod-usb-dwc3"
PACKAGES="$PACKAGES kmod-usb-ehci"
PACKAGES="$PACKAGES kmod-usb-storage"
PACKAGES="$PACKAGES kmod-usb-xhci-hcd"
PACKAGES="$PACKAGES kmod-usb2"
PACKAGES="$PACKAGES kmod-usb3"
PACKAGES="$PACKAGES kmod-veth"

# --------------------------------------------------------
# 库文件 (必须保留)
# --------------------------------------------------------
PACKAGES="$PACKAGES libacl"
PACKAGES="$PACKAGES libatomic1"
PACKAGES="$PACKAGES libattr"
PACKAGES="$PACKAGES libblkid1"
PACKAGES="$PACKAGES libblobmsg-json20240329"
PACKAGES="$PACKAGES libbpf1"
PACKAGES="$PACKAGES libbz2-1.0"
PACKAGES="$PACKAGES libc"
PACKAGES="$PACKAGES libcap"
PACKAGES="$PACKAGES libcap-ng"
PACKAGES="$PACKAGES libcomerr0"
PACKAGES="$PACKAGES libcurl4"
PACKAGES="$PACKAGES libdbus"
PACKAGES="$PACKAGES libdevmapper"
PACKAGES="$PACKAGES libe2p2"
PACKAGES="$PACKAGES libelf1"
PACKAGES="$PACKAGES libevdev"
PACKAGES="$PACKAGES libevent2-7"
PACKAGES="$PACKAGES libexpat"
PACKAGES="$PACKAGES libext2fs2"
PACKAGES="$PACKAGES libfdisk1"
PACKAGES="$PACKAGES libffi"
PACKAGES="$PACKAGES libfuse1"
PACKAGES="$PACKAGES libgcc1"
PACKAGES="$PACKAGES libgcrypt"
PACKAGES="$PACKAGES libgdbm"
PACKAGES="$PACKAGES libgmp10"
PACKAGES="$PACKAGES libgnutls"
PACKAGES="$PACKAGES libgpg-error"
PACKAGES="$PACKAGES libiperf3"
PACKAGES="$PACKAGES libiptext-nft0"
PACKAGES="$PACKAGES libiptext0"
PACKAGES="$PACKAGES libiwinfo-data"
PACKAGES="$PACKAGES libiwinfo20230701"
PACKAGES="$PACKAGES libjson-c5"
PACKAGES="$PACKAGES libjson-script20240329"
PACKAGES="$PACKAGES libkeyutils1"
PACKAGES="$PACKAGES libkmod"
PACKAGES="$PACKAGES liblua5.1.5"
PACKAGES="$PACKAGES liblucihttp-lua"
PACKAGES="$PACKAGES liblucihttp-ucode"
PACKAGES="$PACKAGES liblucihttp0"
PACKAGES="$PACKAGES liblzma"
PACKAGES="$PACKAGES liblzo2"
PACKAGES="$PACKAGES libmbedtls21"
PACKAGES="$PACKAGES libmnl0"
PACKAGES="$PACKAGES libmount1"
PACKAGES="$PACKAGES libncurses6"
PACKAGES="$PACKAGES libneon"
PACKAGES="$PACKAGES libnetfilter-conntrack3"
PACKAGES="$PACKAGES libnettle8"
PACKAGES="$PACKAGES libnfnetlink0"
PACKAGES="$PACKAGES libnftnl11"
PACKAGES="$PACKAGES libnghttp2-14"
PACKAGES="$PACKAGES libnl-tiny1"
PACKAGES="$PACKAGES libopenssl-conf"
PACKAGES="$PACKAGES libopenssl-legacy"
PACKAGES="$PACKAGES libopenssl3"
PACKAGES="$PACKAGES libpcap1"
PACKAGES="$PACKAGES libpci"
PACKAGES="$PACKAGES libpcre2"
PACKAGES="$PACKAGES libpopt0"
PACKAGES="$PACKAGES libpthread"
PACKAGES="$PACKAGES libreadline8"
PACKAGES="$PACKAGES librt"
PACKAGES="$PACKAGES libseccomp"
PACKAGES="$PACKAGES libsensors5"
PACKAGES="$PACKAGES libsmartcols1"
PACKAGES="$PACKAGES libss2"
PACKAGES="$PACKAGES libstdcpp6"
PACKAGES="$PACKAGES libsysfs2"
PACKAGES="$PACKAGES libtasn1"
PACKAGES="$PACKAGES libtirpc"
PACKAGES="$PACKAGES libubox20240329"
PACKAGES="$PACKAGES libubus-lua"
PACKAGES="$PACKAGES libubus20250102"
PACKAGES="$PACKAGES libuci-lua"
PACKAGES="$PACKAGES libuci20250120"
PACKAGES="$PACKAGES libuclient20201210"
PACKAGES="$PACKAGES libucode20230711"
PACKAGES="$PACKAGES libudebug"
PACKAGES="$PACKAGES libudev-zero"
PACKAGES="$PACKAGES liburing"
PACKAGES="$PACKAGES libusb-1.0-0"
PACKAGES="$PACKAGES libuuid1"
PACKAGES="$PACKAGES libuv1"
PACKAGES="$PACKAGES libwebsockets-full"
PACKAGES="$PACKAGES libwrap"
PACKAGES="$PACKAGES libxtables12"
PACKAGES="$PACKAGES libzstd"

# --------------------------------------------------------
# 服务与应用 (根据旁路由和iStoreOS功能保留)
# --------------------------------------------------------
PACKAGES="$PACKAGES avahi-dbus-daemon"
PACKAGES="$PACKAGES avahi-utils"
PACKAGES="$PACKAGES badblocks"
PACKAGES="$PACKAGES blkid"
PACKAGES="$PACKAGES block-mount"
PACKAGES="$PACKAGES btrfs-progs"
PACKAGES="$PACKAGES dbus"
PACKAGES="$PACKAGES -dnsmasq"
PACKAGES="$PACKAGES dnsmasq-full" # 核心 DNS/DHCP 服务
PACKAGES="$PACKAGES firewall4"
PACKAGES="$PACKAGES fdisk"
PACKAGES="$PACKAGES grub2-efi-arm" # 用于启动
PACKAGES="$PACKAGES iperf3"
PACKAGES="$PACKAGES jansson4"
PACKAGES="$PACKAGES linkease"
PACKAGES="$PACKAGES linkmount"
PACKAGES="$PACKAGES losetup"
PACKAGES="$PACKAGES luci"
PACKAGES="$PACKAGES luci-app-argon-config"
PACKAGES="$PACKAGES luci-app-cifs-mount"
PACKAGES="$PACKAGES luci-app-cpufreq"
PACKAGES="$PACKAGES luci-app-diskman"
PACKAGES="$PACKAGES luci-app-filetransfer"
PACKAGES="$PACKAGES luci-app-firewall"
PACKAGES="$PACKAGES luci-app-linkease"
PACKAGES="$PACKAGES luci-app-mergerfs"
PACKAGES="$PACKAGES luci-app-nfs"
PACKAGES="$PACKAGES luci-app-ota"
PACKAGES="$PACKAGES luci-app-package-manager"
PACKAGES="$PACKAGES luci-app-quickstart"
PACKAGES="$PACKAGES luci-app-samba4"
PACKAGES="$PACKAGES luci-app-store"
PACKAGES="$PACKAGES luci-app-ttyd"
#PACKAGES="$PACKAGES luci-app-unishare"
PACKAGES="$PACKAGES luci-app-wol"
PACKAGES="$PACKAGES luci-base"
PACKAGES="$PACKAGES luci-compat"
PACKAGES="$PACKAGES luci-i18n-argon-config-zh-cn"
PACKAGES="$PACKAGES luci-i18n-argon-zh-cn"
PACKAGES="$PACKAGES luci-i18n-base-zh-cn"
PACKAGES="$PACKAGES luci-i18n-cifs-mount-zh-cn"
PACKAGES="$PACKAGES luci-i18n-cpufreq-zh-cn"
PACKAGES="$PACKAGES luci-i18n-diskman-zh-cn"
PACKAGES="$PACKAGES luci-i18n-filetransfer-zh-cn"
PACKAGES="$PACKAGES luci-i18n-firewall-zh-cn"
PACKAGES="$PACKAGES luci-i18n-linkease-zh-cn"
PACKAGES="$PACKAGES luci-i18n-mergerfs-zh-cn"
PACKAGES="$PACKAGES luci-i18n-nfs-zh-cn"
PACKAGES="$PACKAGES luci-i18n-ota-zh-cn"
PACKAGES="$PACKAGES luci-i18n-package-manager-zh-cn"
PACKAGES="$PACKAGES luci-i18n-quickstart-zh-cn"
PACKAGES="$PACKAGES luci-i18n-samba4-zh-cn"
PACKAGES="$PACKAGES luci-i18n-ttyd-zh-cn"
#PACKAGES="$PACKAGES luci-i18n-unishare-zh-cn"
PACKAGES="$PACKAGES luci-i18n-wol-zh-cn"
PACKAGES="$PACKAGES luci-lib-base"
PACKAGES="$PACKAGES luci-lib-fs"
PACKAGES="$PACKAGES luci-lib-ip"
PACKAGES="$PACKAGES luci-lib-ipkg"
PACKAGES="$PACKAGES luci-lib-jsonc"
PACKAGES="$PACKAGES luci-lib-nixio"
PACKAGES="$PACKAGES luci-lib-taskd"
PACKAGES="$PACKAGES luci-lib-xterm"
PACKAGES="$PACKAGES luci-light"
PACKAGES="$PACKAGES luci-lua-runtime"
PACKAGES="$PACKAGES luci-mod-admin-full"
PACKAGES="$PACKAGES luci-mod-network"
PACKAGES="$PACKAGES luci-mod-status"
PACKAGES="$PACKAGES luci-mod-system"
PACKAGES="$PACKAGES luci-proto-external"
PACKAGES="$PACKAGES luci-proto-ppp"
PACKAGES="$PACKAGES luci-ssl"
PACKAGES="$PACKAGES luci-theme-argon"
PACKAGES="$PACKAGES mdadm"
PACKAGES="$PACKAGES mergerfs"
PACKAGES="$PACKAGES miniupnpd-nftables"
PACKAGES="$PACKAGES mkf2fs"
PACKAGES="$PACKAGES nfs-kernel-server"
PACKAGES="$PACKAGES nfs-kernel-server-utils"
PACKAGES="$PACKAGES nfs-utils"
PACKAGES="$PACKAGES nfs-utils-libs"
PACKAGES="$PACKAGES ntfs3-mount"
PACKAGES="$PACKAGES ntfsprogs"
PACKAGES="$PACKAGES openssh-sftp-server"
PACKAGES="$PACKAGES parted"
PACKAGES="$PACKAGES partx-utils"
PACKAGES="$PACKAGES pciids"
PACKAGES="$PACKAGES pciutils"
PACKAGES="$PACKAGES ppp"
PACKAGES="$PACKAGES ppp-mod-pppoe"
PACKAGES="$PACKAGES proto-bonding"
PACKAGES="$PACKAGES px5g-mbedtls"
PACKAGES="$PACKAGES quickstart"
PACKAGES="$PACKAGES relayd"
PACKAGES="$PACKAGES resize2fs"
PACKAGES="$PACKAGES rpcbind"
PACKAGES="$PACKAGES samba4-libs"
PACKAGES="$PACKAGES samba4-server"
PACKAGES="$PACKAGES smartmontools"
PACKAGES="$PACKAGES taskd"
PACKAGES="$PACKAGES tcpdump"
PACKAGES="$PACKAGES tini"
PACKAGES="$PACKAGES ttyd"
PACKAGES="$PACKAGES tune2fs"
PACKAGES="$PACKAGES usbids"
PACKAGES="$PACKAGES usbutils"
PACKAGES="$PACKAGES wpa-cli"
PACKAGES="$PACKAGES wpa-supplicant-openssl"
PACKAGES="$PACKAGES wsdd2"
PACKAGES="$PACKAGES zram-swap"
PACKAGES="$PACKAGES -libustream-mbedtls"
PACKAGES="$PACKAGES -luci-app-netspeedtest"

# 强制排除所有干扰项 (重点解决您的编译失败问题)
# --------------------------------------------------------
PACKAGES="$PACKAGES \
-rtl8192cu-firmware -rtl8192de-firmware -rtl8192se-firmware -rtl8723de-firmware -rtl8812a-firmware -rtl8821a-firmware -rtl8821ae-firmware -rtl8821ce-firmware -rtl8822be-firmware -rtl8822ce-firmware -rtl8851be-firmware -rtl8852ae-firmware -rtl8852be-firmware -rtl8852ce-firmware -rtl8922ae-firmware \
-luci-i18n-unishare-zh-cn -luci-app-netspeedtest \
-ddns-scripts -ddns-scripts-cloudflare -ddns-scripts-dnspod -ddns-scripts-services -ddns-scripts_aliyun -ddnsto -luci-app-ddns -luci-app-ddnsto \
-odhcp6c -odhcpd-ipv6only \
-kmod-vmxnet3 -kmod-bcmgenet -kmod-dwmac-sun8i -kmod-phy-smsc -kmod-phy-marvell-10g -kmod-mdio -kmod-mdio-bcm-unimac \
-kmod-ath10k -kmod-ath11k -kmod-ath12k -kmod-mt76-core -kmod-mt7915e -kmod-mt7921e \
-kmod-rtl8192cu -kmod-rtl8192de -kmod-rtw88 -kmod-rtw89 \
-bnx2x-firmware -e100-firmware -qed-firmware -mwifiex-pcie-firmware \
-r8152-firmware -r8169-firmware \
"

# 固件打包脚本必要依赖，其他依赖官方列表已集成
PACKAGES="$PACKAGES perlbase-time"

# 斐讯N1无线：此固件未考虑无线，需自行研究；其中iw和iwinfo官方列表已集成
#PACKAGES="$PACKAGES kmod-brcmfmac wpad-basic-mbedtls"

# file/packages目录的第三方可选插件
PACKAGES="$PACKAGES filebrowser luci-app-filebrowser-go luci-i18n-filebrowser-go-zh-cn"
PACKAGES="$PACKAGES luci-app-amlogic luci-i18n-amlogic-zh-cn"
PACKAGES="$PACKAGES lucky luci-app-lucky luci-i18n-lucky-zh-cn"
#PACKAGES="$PACKAGES openlist2 luci-app-openlist2 luci-i18n-openlist2-zh-cn"
PACKAGES="$PACKAGES luci-app-ramfree luci-i18n-ramfree-zh-cn"
#PACKAGES="$PACKAGES luci-app-adguardhome luci-i18n-adguardhome-zh-cn"

# opc-rely依赖，其他会自动集成
PACKAGES="$PACKAGES ruby ruby-pstore ruby-psych ruby-yaml"

# 追加自定义包
PACKAGES="$PACKAGES $CUSTOM_PACKAGES"
#PACKAGES="$PACKAGES luci-app-openclash"
#PACKAGES="$PACKAGES mosdns luci-app-mosdns luci-i18n-mosdns-zh-cn"
#PACKAGES="$PACKAGES vlmcsd luci-app-vlmcsd luci-i18n-vlmcsd-zh-cn"

# 构建镜像
echo "开始构建......打印所有包名===="
echo "$PACKAGES"

# 开始构建
make image PROFILE=generic PACKAGES="$PACKAGES" FILES="files"

if [ $? -ne 0 ]; then
    echo "$(date '+%Y-%m-%d %H:%M:%S') - Error: Build failed!"
    exit 1
fi

echo "$(date '+%Y-%m-%d %H:%M:%S') - 构建成功."
